{% set name = "pickydict" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pickydict-{{ version }}.tar.gz
  sha256: fc66944dc5782c1078ffe41cf4dd8fdf6702f9d63c5373748403c12ea2da8cc6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - pickydict
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/florian-huber/pickydict
  summary: |
    More picky version of Python dictionary.
    PickyDict objects will behave just like Python dictionaries, with a few notable exceptions.
    PickyDict has a force_lower_case attribute. and PickyDict can contain two additional dictionaries
    named key_replacements and key_regex_replacements with mappings to enforce translating specific key words.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - florian-huber
